services:
  - type: web
    name: saumya-mishra-project3
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm run prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 25.8.1
      - key: CLIENT_ORIGIN
        sync: false
      - key: COOKIE_NAME
        value: sudoku_session
      - key: MONGO
        sync: false
      - key: MONGODB_URI
        sync: false
