const WORD_POOL = [
  "Acorn", "Anchor", "Apple", "Apricot", "Arbor", "Arc", "Arrow", "Ash", "Aspen", "Aster",
  "Atlas", "Aurora", "Autumn", "Avalanche", "Avenue", "Azure", "Baker", "Bamboo", "Banner", "Bay",
  "Beacon", "Bear", "Berry", "Birch", "Blaze", "Bloom", "Blossom", "Bluebird", "Boat", "Boulder",
  "Breeze", "Brook", "Buttercup", "Cactus", "Candle", "Canyon", "Cascade", "Castle", "Cedar", "Celery",
  "Center", "Cherry", "Cinder", "Circle", "Cliff", "Cloud", "Clover", "Coast", "Comet", "Coral",
  "Corner", "Cosmos", "Cottage", "Creek", "Crest", "Cricket", "Crown", "Crystal", "Current", "Cypress",
  "Daffodil", "Dawn", "Delta", "Desert", "Diamond", "Dove", "Dragonfly", "Drift", "Dune", "Eagle",
  "Earth", "Echo", "Eclipse", "Elm", "Ember", "Emerald", "Falcon", "Feather", "Fern", "Field",
  "Finch", "Firefly", "Flame", "Flint", "Flower", "Fog", "Forest", "Fox", "Frost", "Garden",
  "Garnet", "Glade", "Glen", "Glow", "Goldfinch", "Granite", "Grass", "Grove", "Harbor", "Harmony",
  "Hazel", "Heather", "Heron", "Hill", "Horizon", "House", "Iceberg", "Iris", "Island", "Ivory",
  "Jade", "Jasper", "Juniper", "Kingfisher", "Lagoon", "Lake", "Lantern", "Laurel", "Leaf", "Lemon",
  "Lilac", "Lily", "Maple", "Marble", "Marsh", "Meadow", "Melody", "Mesa", "Mist", "Monarch",
  "Moon", "Morning", "Moss", "Mountain", "Nectar", "Nest", "North", "Oak", "Ocean", "Olive",
  "Onyx", "Orchid", "Osprey", "Pebble", "Pine", "Planet", "Plum", "Pond", "Prairie", "Quartz",
  "Raven", "Redwood", "Reef", "Reserve", "Ridge", "River", "Robin", "Rose", "Sage", "Sand",
  "Seashell", "Shadow", "Shore", "Silver", "Sky", "Snow", "Solar", "Song", "South", "Spark",
  "Spring", "Spruce", "Star", "Stone", "Stream", "Summit", "Sunrise", "Sunset", "Swift", "Sycamore",
  "Temple", "Thorn", "Thunder", "Trail", "Tree", "Tulip", "Valley", "Violet", "Voyage", "Willow",
  "Wind", "Winter", "Wood", "Wren",
  "Acorn1", "Anchor1", "Apple1", "Apricot1", "Arbor1", "Arc1", "Arrow1", "Ash1", "Aspen1", "Aster1",
  "Atlas1", "Aurora1", "Autumn1", "Avalanche1", "Avenue1", "Azure1", "Baker1", "Bamboo1", "Banner1", "Bay1",
  "Beacon1", "Bear1", "Berry1", "Birch1", "Blaze1", "Bloom1", "Blossom1", "Bluebird1", "Boat1", "Boulder1",
  "Breeze1", "Brook1", "Buttercup1", "Cactus1", "Candle1", "Canyon1", "Cascade1", "Castle1", "Cedar1", "Celery1",
  "Center1", "Cherry1", "Cinder1", "Circle1", "Cliff1", "Cloud1", "Clover1", "Coast1", "Comet1", "Coral1",
  "Corner1", "Cosmos1", "Cottage1", "Creek1", "Crest1", "Cricket1", "Crown1", "Crystal1", "Current1", "Cypress1",
  "Daffodil1", "Dawn1", "Delta1", "Desert1", "Diamond1", "Dove1", "Dragonfly1", "Drift1", "Dune1", "Eagle1",
  "Earth1", "Echo1", "Eclipse1", "Elm1", "Ember1", "Emerald1", "Falcon1", "Feather1", "Fern1", "Field1",
  "Finch1", "Firefly1", "Flame1", "Flint1", "Flower1", "Fog1", "Forest1", "Fox1", "Frost1", "Garden1",
  "Garnet1", "Glade1", "Glen1", "Glow1", "Goldfinch1", "Granite1", "Grass1", "Grove1", "Harbor1", "Harmony1",
  "Hazel1", "Heather1", "Heron1", "Hill1", "Horizon1", "House1", "Iceberg1", "Iris1", "Island1", "Ivory1",
  "Jade1", "Jasper1", "Juniper1", "Kingfisher1", "Lagoon1", "Lake1", "Lantern1", "Laurel1", "Leaf1", "Lemon1",
  "Lilac1", "Lily1", "Maple1", "Marble1", "Marsh1", "Meadow1", "Melody1", "Mesa1", "Mist1", "Monarch1",
  "Moon1", "Morning1", "Moss1", "Mountain1", "Nectar1", "Nest1", "North1", "Oak1", "Ocean1", "Olive1",
  "Onyx1", "Orchid1", "Osprey1", "Pebble1", "Pine1", "Planet1", "Plum1", "Pond1", "Prairie1", "Quartz1",
  "Raven1", "Redwood1", "Reef1", "Reserve1", "Ridge1", "River1", "Robin1", "Rose1", "Sage1", "Sand1",
  "Seashell1", "Shadow1", "Shore1", "Silver1", "Sky1", "Snow1", "Solar1", "Song1", "South1", "Spark1",
  "Spring1", "Spruce1", "Star1", "Stone1", "Stream1", "Summit1", "Sunrise1", "Sunset1", "Swift1", "Sycamore1",
  "Temple1", "Thorn1", "Thunder1", "Trail1", "Tree1", "Tulip1", "Valley1", "Violet1", "Voyage1", "Willow1",
  "Wind1", "Winter1", "Wood1", "Wren1",
  "Acorn2", "Anchor2", "Apple2", "Apricot2", "Arbor2", "Arc2", "Arrow2", "Ash2", "Aspen2", "Aster2",
  "Atlas2", "Aurora2", "Autumn2", "Avalanche2", "Avenue2", "Azure2", "Baker2", "Bamboo2", "Banner2", "Bay2",
  "Beacon2", "Bear2", "Berry2", "Birch2", "Blaze2", "Bloom2", "Blossom2", "Bluebird2", "Boat2", "Boulder2",
  "Breeze2", "Brook2", "Buttercup2", "Cactus2", "Candle2", "Canyon2", "Cascade2", "Castle2", "Cedar2", "Celery2",
  "Center2", "Cherry2", "Cinder2", "Circle2", "Cliff2", "Cloud2", "Clover2", "Coast2", "Comet2", "Coral2",
  "Corner2", "Cosmos2", "Cottage2", "Creek2", "Crest2", "Cricket2", "Crown2", "Crystal2", "Current2", "Cypress2",
  "Daffodil2", "Dawn2", "Delta2", "Desert2", "Diamond2", "Dove2", "Dragonfly2", "Drift2", "Dune2", "Eagle2",
  "Earth2", "Echo2", "Eclipse2", "Elm2", "Ember2", "Emerald2", "Falcon2", "Feather2", "Fern2", "Field2",
  "Finch2", "Firefly2", "Flame2", "Flint2", "Flower2", "Fog2", "Forest2", "Fox2", "Frost2", "Garden2",
  "Garnet2", "Glade2", "Glen2", "Glow2", "Goldfinch2", "Granite2", "Grass2", "Grove2", "Harbor2", "Harmony2",
  "Hazel2", "Heather2", "Heron2", "Hill2", "Horizon2", "House2", "Iceberg2", "Iris2", "Island2", "Ivory2",
  "Jade2", "Jasper2", "Juniper2", "Kingfisher2", "Lagoon2", "Lake2", "Lantern2", "Laurel2", "Leaf2", "Lemon2",
  "Lilac2", "Lily2", "Maple2", "Marble2", "Marsh2", "Meadow2", "Melody2", "Mesa2", "Mist2", "Monarch2",
  "Moon2", "Morning2", "Moss2", "Mountain2", "Nectar2", "Nest2", "North2", "Oak2", "Ocean2", "Olive2",
  "Onyx2", "Orchid2", "Osprey2", "Pebble2", "Pine2", "Planet2", "Plum2", "Pond2", "Prairie2", "Quartz2",
  "Raven2", "Redwood2", "Reef2", "Reserve2", "Ridge2", "River2", "Robin2", "Rose2", "Sage2", "Sand2",
  "Seashell2", "Shadow2", "Shore2", "Silver2", "Sky2", "Snow2", "Solar2", "Song2", "South2", "Spark2",
  "Spring2", "Spruce2", "Star2", "Stone2", "Stream2", "Summit2", "Sunrise2", "Sunset2", "Swift2", "Sycamore2",
  "Temple2", "Thorn2", "Thunder2", "Trail2", "Tree2", "Tulip2", "Valley2", "Violet2", "Voyage2", "Willow2",
  "Wind2", "Winter2", "Wood2", "Wren2",
  "Acorn3", "Anchor3", "Apple3", "Apricot3", "Arbor3", "Arc3", "Arrow3", "Ash3", "Aspen3", "Aster3",
  "Atlas3", "Aurora3", "Autumn3", "Avalanche3", "Avenue3", "Azure3", "Baker3", "Bamboo3", "Banner3", "Bay3",
  "Beacon3", "Bear3", "Berry3", "Birch3", "Blaze3", "Bloom3", "Blossom3", "Bluebird3", "Boat3", "Boulder3",
  "Breeze3", "Brook3", "Buttercup3", "Cactus3", "Candle3", "Canyon3", "Cascade3", "Castle3", "Cedar3", "Celery3",
  "Center3", "Cherry3", "Cinder3", "Circle3", "Cliff3", "Cloud3", "Clover3", "Coast3", "Comet3", "Coral3",
  "Corner3", "Cosmos3", "Cottage3", "Creek3", "Crest3", "Cricket3", "Crown3", "Crystal3", "Current3", "Cypress3",
  "Daffodil3", "Dawn3", "Delta3", "Desert3", "Diamond3", "Dove3", "Dragonfly3", "Drift3", "Dune3", "Eagle3",
  "Earth3", "Echo3", "Eclipse3", "Elm3", "Ember3", "Emerald3", "Falcon3", "Feather3", "Fern3", "Field3",
  "Finch3", "Firefly3", "Flame3", "Flint3", "Flower3", "Fog3", "Forest3", "Fox3", "Frost3", "Garden3",
  "Garnet3", "Glade3", "Glen3", "Glow3", "Goldfinch3", "Granite3", "Grass3", "Grove3", "Harbor3", "Harmony3",
  "Hazel3", "Heather3", "Heron3", "Hill3", "Horizon3", "House3", "Iceberg3", "Iris3", "Island3", "Ivory3",
  "Jade3", "Jasper3", "Juniper3", "Kingfisher3", "Lagoon3", "Lake3", "Lantern3", "Laurel3", "Leaf3", "Lemon3",
  "Lilac3", "Lily3", "Maple3", "Marble3", "Marsh3", "Meadow3", "Melody3", "Mesa3", "Mist3", "Monarch3",
  "Moon3", "Morning3", "Moss3", "Mountain3", "Nectar3", "Nest3", "North3", "Oak3", "Ocean3", "Olive3",
  "Onyx3", "Orchid3", "Osprey3", "Pebble3", "Pine3", "Planet3", "Plum3", "Pond3", "Prairie3", "Quartz3",
  "Raven3", "Redwood3", "Reef3", "Reserve3", "Ridge3", "River3", "Robin3", "Rose3", "Sage3", "Sand3",
  "Seashell3", "Shadow3", "Shore3", "Silver3", "Sky3", "Snow3", "Solar3", "Song3", "South3", "Spark3",
  "Spring3", "Spruce3", "Star3", "Stone3", "Stream3", "Summit3", "Sunrise3", "Sunset3", "Swift3", "Sycamore3",
  "Temple3", "Thorn3", "Thunder3", "Trail3", "Tree3", "Tulip3", "Valley3", "Violet3", "Voyage3", "Willow3",
  "Wind3", "Winter3", "Wood3", "Wren3",
  "Acorn4", "Anchor4", "Apple4", "Apricot4", "Arbor4", "Arc4", "Arrow4", "Ash4", "Aspen4", "Aster4",
  "Atlas4", "Aurora4", "Autumn4", "Avalanche4", "Avenue4", "Azure4", "Baker4", "Bamboo4", "Banner4", "Bay4",
  "Beacon4", "Bear4", "Berry4", "Birch4", "Blaze4", "Bloom4", "Blossom4", "Bluebird4", "Boat4", "Boulder4",
  "Breeze4", "Brook4", "Buttercup4", "Cactus4", "Candle4", "Canyon4", "Cascade4", "Castle4", "Cedar4", "Celery4",
  "Center4", "Cherry4", "Cinder4", "Circle4", "Cliff4", "Cloud4", "Clover4", "Coast4", "Comet4", "Coral4",
  "Corner4", "Cosmos4", "Cottage4", "Creek4", "Crest4", "Cricket4", "Crown4", "Crystal4", "Current4", "Cypress4",
  "Daffodil4", "Dawn4", "Delta4", "Desert4", "Diamond4", "Dove4", "Dragonfly4", "Drift4", "Dune4", "Eagle4",
  "Earth4", "Echo4", "Eclipse4", "Elm4", "Ember4", "Emerald4", "Falcon4", "Feather4", "Fern4", "Field4",
  "Finch4", "Firefly4", "Flame4", "Flint4", "Flower4", "Fog4", "Forest4", "Fox4", "Frost4", "Garden4",
  "Garnet4", "Glade4", "Glen4", "Glow4", "Goldfinch4", "Granite4", "Grass4", "Grove4", "Harbor4", "Harmony4",
  "Hazel4", "Heather4", "Heron4", "Hill4", "Horizon4", "House4", "Iceberg4", "Iris4", "Island4", "Ivory4",
  "Jade4", "Jasper4", "Juniper4", "Kingfisher4", "Lagoon4", "Lake4", "Lantern4", "Laurel4", "Leaf4", "Lemon4",
  "Lilac4", "Lily4", "Maple4", "Marble4", "Marsh4", "Meadow4", "Melody4", "Mesa4", "Mist4", "Monarch4",
  "Moon4", "Morning4", "Moss4", "Mountain4", "Nectar4", "Nest4", "North4", "Oak4", "Ocean4", "Olive4",
  "Onyx4", "Orchid4", "Osprey4", "Pebble4", "Pine4", "Planet4", "Plum4", "Pond4", "Prairie4", "Quartz4",
  "Raven4", "Redwood4", "Reef4", "Reserve4", "Ridge4", "River4", "Robin4", "Rose4", "Sage4", "Sand4",
  "Seashell4", "Shadow4", "Shore4", "Silver4", "Sky4", "Snow4", "Solar4", "Song4", "South4", "Spark4",
  "Spring4", "Spruce4", "Star4", "Stone4", "Stream4", "Summit4", "Sunrise4", "Sunset4", "Swift4", "Sycamore4",
  "Temple4", "Thorn4", "Thunder4", "Trail4", "Tree4", "Tulip4", "Valley4", "Violet4", "Voyage4", "Willow4",
  "Wind4", "Winter4", "Wood4", "Wren4",
  "Acorn5", "Anchor5", "Apple5", "Apricot5", "Arbor5", "Arc5", "Arrow5", "Ash5", "Aspen5", "Aster5",
  "Atlas5", "Aurora5", "Autumn5", "Avalanche5", "Avenue5", "Azure5", "Baker5", "Bamboo5", "Banner5", "Bay5",
  "Beacon5", "Bear5", "Berry5", "Birch5", "Blaze5", "Bloom5", "Blossom5", "Bluebird5", "Boat5", "Boulder5",
  "Breeze5", "Brook5", "Buttercup5", "Cactus5", "Candle5", "Canyon5", "Cascade5", "Castle5", "Cedar5", "Celery5",
  "Center5", "Cherry5", "Cinder5", "Circle5", "Cliff5", "Cloud5", "Clover5", "Coast5", "Comet5", "Coral5",
  "Corner5", "Cosmos5", "Cottage5", "Creek5", "Crest5", "Cricket5", "Crown5", "Crystal5", "Current5", "Cypress5",
  "Daffodil5", "Dawn5", "Delta5", "Desert5", "Diamond5", "Dove5", "Dragonfly5", "Drift5", "Dune5", "Eagle5",
  "Earth5", "Echo5", "Eclipse5", "Elm5", "Ember5", "Emerald5", "Falcon5", "Feather5", "Fern5", "Field5",
  "Finch5", "Firefly5", "Flame5", "Flint5", "Flower5", "Fog5", "Forest5", "Fox5", "Frost5", "Garden5",
  "Garnet5", "Glade5", "Glen5", "Glow5", "Goldfinch5", "Granite5", "Grass5", "Grove5", "Harbor5", "Harmony5",
  "Hazel5", "Heather5", "Heron5", "Hill5", "Horizon5", "House5", "Iceberg5", "Iris5", "Island5", "Ivory5",
  "Jade5", "Jasper5", "Juniper5", "Kingfisher5", "Lagoon5", "Lake5", "Lantern5", "Laurel5", "Leaf5", "Lemon5",
  "Lilac5", "Lily5", "Maple5", "Marble5", "Marsh5", "Meadow5", "Melody5", "Mesa5", "Mist5", "Monarch5",
  "Moon5", "Morning5", "Moss5", "Mountain5", "Nectar5", "Nest5", "North5", "Oak5", "Ocean5", "Olive5",
  "Onyx5", "Orchid5", "Osprey5", "Pebble5", "Pine5", "Planet5", "Plum5", "Pond5", "Prairie5", "Quartz5",
  "Raven5", "Redwood5", "Reef5", "Reserve5", "Ridge5", "River5", "Robin5", "Rose5", "Sage5", "Sand5",
  "Seashell5", "Shadow5", "Shore5", "Silver5", "Sky5", "Snow5", "Solar5", "Song5", "South5", "Spark5",
  "Spring5", "Spruce5", "Star5", "Stone5", "Stream5", "Summit5", "Sunrise5", "Sunset5", "Swift5", "Sycamore5",
  "Temple5", "Thorn5", "Thunder5", "Trail5", "Tree5", "Tulip5", "Valley5", "Violet5", "Voyage5", "Willow5",
  "Wind5", "Winter5", "Wood5", "Wren5",
];

function shuffle(values) {
  const copy = [...values];

  for (let index = copy.length - 1; index > 0; index -= 1) {
    const swapIndex = Math.floor(Math.random() * (index + 1));
    [copy[index], copy[swapIndex]] = [copy[swapIndex], copy[index]];
  }

  return copy;
}

export function generateGameName() {
  const [first, second, third] = shuffle(WORD_POOL).slice(0, 3);
  return `${first} ${second} ${third}`;
}
